#pragma once

namespace uasm {

namespace SyscallId {
enum Value {
    Exit = 0,
    Write = 1,
    Read = 2,
    Open = 3,
    Close = 4,
    Seek = 5,
    FileSize = 6,
    RemoveFile = 7,
    RenameFile = 8,
    Mkdir = 9,
    Rmdir = 10,
    Getcwd = 11,
    Chdir = 12,
    FileExists = 13,
    Realpath = 14,
    TimeUnixSeconds = 15,
    TimeUnixMillis = 16,
    TickCountMs = 17,
    SleepMillis = 18,
    GetPid = 19,
    CpuCount = 20,
    PageSize = 21,
    GetEnv = 22,
    SetEnv = 23,
    Argc = 24,
    Argv = 25,
    RandomBytes = 26,
    IsATty = 27,
    Flush = 28,
    StdinAvailable = 29,

    DirOpen = 30,
    DirRead = 31,
    DirClose = 32,
    FileIsDir = 33,
    FileMtime = 34,
    FilePermsGet = 35,
    FilePermsSet = 36,
    CopyFile = 37,
    DiskFreeSpace = 38,
    GetTempDir = 39,
    GetExePath = 40,
    GetHostname = 41,
    EnvCount = 42,
    EnvGet = 43,
    TermColumns = 44,
    TermRows = 45,
    FileLock = 46,
    FileUnlock = 47,
    SocketCreate = 48,
    SocketConnect = 49,
    SocketBind = 50,
    SocketListen = 51,
    SocketAccept = 52,
    SocketSend = 53,
    SocketRecv = 54,
    SocketClose = 55,
    DnsResolve = 56,
    MemPageAlloc = 57,
    MemPageProtect = 58,
    CpuArchId = 59
};
}

}
